title: CODENAME:M-00
description: a multi-purpose voicebank Publishing site
theme: just-the-docs

url: https://nanomarcella.github.io/

logo: "/assets/images/M-00-LOGO.png"

favicon_ico: "/assets/images/favicon.ico"
