title: CODENAME:M-00
description: a multi-purpose voicebank Publishing site
theme: just-the-docs

url: https://nanomarcella.github.io/

favicon_ico: "/assets/images/favicon.ico"

permalink: pretty

defaults:
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: "default"

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - LICENSE.txt
  - package.json
  - package-lock.json
  - Rakefile
  - README.md
  - CODE_OF_CONDUCT.md
  - docker-compose.yml
  - Dockerfile
  - fixtures/

search_enabled: true
search:
  heading_level: 2
  previews: 2
  preview_words_before: 3
  preview_words_after: 3
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: true
  focus_shortcut_key: "k"

enable_copy_code_button: true

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.6"
  # Put any additional configuration, such as setting the theme, in _includes/mermaid_config.js
  # See also docs/ui-components/code
  # To load mermaid from a local library, also use the `path` key to specify the location of the library; e.g.
  # for (v10+):
  # path: "/assets/js/mermaid.esm.min.mjs"
  # for (<v10):
  # path: "/assets/js/mermaid.min.js"
  # Note: copy both `mermaid.esm.min.mjs` (v10+) or `mermaid.min.js` (<v10) and the associated `.map` file from the specified version of `mermaid/dist` to `/assets/js/`.

# Enable or disable heading anchors
heading_anchors: true

nav_enabled: true

nav_sort: case_sensitive

nav_error_report: true # default is false/nil.